# Generated by Django 2.2.6 on 2019-11-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_remove_profilemodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='contactNumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
