# Generated by Django 2.2.6 on 2019-11-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20191123_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='How_long_have_you_been_house_hunting',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='Life_style',
            field=models.CharField(blank=True, choices=[('Short Commute to work', 'Short Commute to work'), ('Access to shopping', 'Access to shopping'), ('Vastu Preference', 'Vastu Preference'), ('School Requirements', 'School Requirements')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='Price_Range',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='any_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='bath',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='beds',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='has_pre_approval',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='location_preference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='looking_to_buy_in_how_many_months',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='lot_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='property_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='stories',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
