# Generated by Django 2.2.6 on 2019-11-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20191126_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
